### ISSUE TITLE
elevation_models 

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [ymcmrs/ICAMS#1]
Hi,

I was wondering if you can help me to solve this issue

```
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from icams import elevation_models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'elevation_models' from 'icams' (unknown location)
>>> import icams
>>> 
```

**Comment by ymcmrs** [comment]
Thanks for your feedback.  
Do you have elevation_models.py in icams folder?  as I did not have this error with a quick test.

**Comment by mohseniaref-InSAR** [comment]
yes, I have and it make me surprsied! It doesn't make sense to me. I really don't know what is going wrong!

**Comment by ymcmrs** [comment]
check the script permission and try to make it executable again (e.g., chmod 777 *, all of them are already executable tho).

**Comment by ymcmrs** [comment]
#[](url)

**Comment by ymcmrs** [comment]
Sorry, the issue was closed with a mistake. If any problems just send email to me. Thanks

 

From: Mohammad Mohseni Aref ***@***.***>
Reply-To: ymcmrs/ICAMS ***@***.***>
Date: Tuesday, November 23, 2021 at 12:50 PM
To: ymcmrs/ICAMS ***@***.***>
Cc: Yunmeng Cao ***@***.***>, Comment ***@***.***>
Subject: Re: [ymcmrs/ICAMS] elevation_models (Issue #1)

 

yes, I have and it make me surprsied! It doesn't make sense to me. I really don't know what is going wrong!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alejobeap** [comment]
Hello I had the same problem
    from icams import elevation_models
ModuleNotFoundError: No module named 'icams'

Is possible to help me?
Thanks

Alejandro

**Comment by ymcmrs** [comment]
No module named ‘icams’ should be the problem of setting environment parameters.

Did you do something as below? (linux or OS systems changed a bit)

 

##--------- PyINT ------------------## 

setenv ICAMS_HOME    ~/python/ICAMS      

setenv PYTHONPATH    ${PYTHONPATH}:${ICAMS_HOME}

setenv PATH          ${PATH}:${ICAMS_HOME}/icams

 

In addidition, I cannot find/see the requested issues on github, so if there is any problem, please feel free to send me email ***@***.***) directly.

 

Cheers,

Yunmeng

From: Pedro Alejandro Espín ***@***.***>
Reply-To: ymcmrs/ICAMS ***@***.***>
Date: Wednesday, June 1, 2022 at 5:13 AM
To: ymcmrs/ICAMS ***@***.***>
Cc: Yunmeng Cao ***@***.***>, State change ***@***.***>
Subject: Re: [ymcmrs/ICAMS] elevation_models (Issue #1)

 

Hello I had the same problem
from icams import elevation_models
ModuleNotFoundError: No module named 'icams'

Is possible to help me?
Thanks

Alejandro
