### ISSUE TITLE
`tropo_icams_sar.read_par_orb`: modify to read isce2 `IW1.xml`

### ISSUE THREAD

**Issue by yuankailiu** [ymcmrs/ICAMS#3]
Hello, 

I wonder if you have updated the codes recently to implement the `kringing` method as the default interpolation method in `tropo_icams.py` and/or `tropo_icams_sar.py`?

I am trying to run ICAMS given MIntPy `timeseries.h5` and `geometryGeo.h5` as input. But it looks like several places in both scripts need to be updated to replace the deprecated `sklm` method with kriging.

In the README.md, the suggested MintPy user command lines:
```
 tropo_icams_sar.py  or  tropo_icams.py

 e.g. :
    tropo_icams_sar.py geometryRadar.h5 --date 20180101 
    tropo_icams.py timeseries.h5 geometryRadar.h5 --project zenith --method sklm
    tropo_icams.py timeseries.h5 geometryRadar.h5 --sar-par 20181025.slc.par --project los --method sklm    (if you are a GAMMA user) 
```

**Comment by yuankailiu** [comment]
Not exactly a big issue, I think `sklm` keyword can be easily replaced by `kriging`. 
Also, I can try edit the code to read the incidenceAngle from the geometry file. 

But if you already have an updated version code, that would be great though!

**Comment by ymcmrs** [comment]
Hello,

Yes, you can use ‘–project zenith’ (default) for without GAMMA-par file, as no need to read orbital datas from the par file.
If you have incidenceAngle in geometryRadar, yes, it’s perfect, if no, you can add one use –incAngle

There are several modifications in PyKrige, please isntall this version:
$CONDA_PREFIX/bin/pip install git+https://github.com/ymcmrs/PyKrige.git

One example of tropo_icams_sar.py:
tropo_icams_sar.py geometryRadar.h5 –date 20180101 –ref-file velocity.h5
Here use ref-file is to provide imaging timing, earth radium, etc, as which are not always included in geoemtryRadar, and you also don’t provide slc-par here.

One example of tropo_icams.py:
tropo_icams.py timeseries.h5 geometryRadar.h5 –ref-file velocity.h5
Here is a bit stupid to call -ref-file again, as tropo_icams_sar.py is called, and not as sub-function, you can modify this easily.

Using tropo_icams_sar.py as an independent script (not a sub-function in tropo_icams.py), is to make it more flexible, particularly for High-performance-computer users.

Hope this helps
Cheers
Yunmeng
From: Yuan-Kai Liu ***@***.***>
Reply to: ymcmrs/ICAMS ***@***.***>
Date: Wednesday, 19 April 2023 at 11:29 AM
To: ymcmrs/ICAMS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ymcmrs/ICAMS] updated code for `kriging` (Issue #3)


Not exactly a big issue, I think sklm keyword can be easily replaced by kriging.
Also, I can try edit the code to read the incidenceAngle from the geometry file.

But if you already have an updated version code, that would be great though!

**Comment by yuankailiu** [comment]
Hi @ymcmrs,

Thanks for your reply. I do have Krigie installed via `$CONDA_PREFIX/bin/pip install git+https://github.com/ymcmrs/PyKrige.git
`
Thanks for updating that `--ref-file` in `tropo_icams_sar.py` so quickly.

But if I want to do the LOS integral delay (instead of projecting zenith to LOS), I will need the GAMMA-par file, correct?

**Comment by ymcmrs** [comment]
Yes, if you want to do LOS integral, you need to provide slc-par file or any other file can provide orbital data, and currently only support GAMMA par.
But it’s easy to read other software-based par files, e.g., check read_par_orb function in tropo_icams_sar.py

From: Yuan-Kai Liu ***@***.***>
Reply to: ymcmrs/ICAMS ***@***.***>
Date: Wednesday, 19 April 2023 at 12:03 PM
To: ymcmrs/ICAMS ***@***.***>
Cc: Yunmeng Cao ***@***.***>, Mention ***@***.***>
Subject: Re: [ymcmrs/ICAMS] updated code for `kriging` (Issue #3)


Hi @ymcmrs<https://github.com/ymcmrs>,

Thanks for your reply. I do have Krigie installed via $CONDA_PREFIX/bin/pip install git+https://github.com/ymcmrs/PyKrige.git
Thanks for updating that --ref-file in tropo_icams_sar.py so quickly.

But if I want to do the LOS integral delay (instead of projecting zenith to LOS), I will need the GAMMA-par file, correct?

**Comment by yuankailiu** [comment]
I see. Could you provide me with one of such `SAR.slc.par` file for me? I can try and see what is the required format and in/outputs. That would be helpful. Thanks.

It looks like I only need one (e.g., `SAR.slc.par`) where it has the orbit info of all acquisitions.

**Comment by yuankailiu** [comment]
In GAMMA, each interferogram has its own `YYYYMMDD.slc.par` listing the orbit states.

When I do time series correction, `tropo_icams.py timeseries.h5 geometryRadar.h5 --sar-par SAR.slc.par`, this single `SAR.slc.par` should contain all the orbit states from all the dates?

**Comment by ymcmrs** [comment]
almost the same. given ~100m position shift to ~800km

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yuankailiu** [comment]
ah, okay, thanks!

**Comment by yuankailiu** [comment]
Reading orbits and timings from ISCE2 IW*.xml works well for me. Thanks

Just a follow-up question about computation. I am working on a longer track spanning ~6 latitude degrees across 7 SAR tracks.
The [`get_LOS_parameters`](https://github.com/ymcmrs/ICAMS/blob/main/icams/tropo_icams_sar.py#L439-L440) (Start to calc LOS atmospheric parameters ...) step seems to be the most time-consuming part. I assume this is not parallelized now (`OMP_NUM_THREADS`) now? 

Have you run into an issue that runs super slow? E.g., only calculates 20 dates of LOS parameters with 12 hours of computation.

**Comment by ymcmrs** [comment]
Well done! Good to know xml file works well for you.

Regarding to get_LOS_parameteres, because tropo_icams.py calls ‘tropo_icams_sar.py’, so for each SAR image, the ‘LOS locations’ would be calculated repeatedly, which does take some time and not necessary since all of the images share the same ‘LOS location’.

So if you are trying to process time-series of datasets, one option to improve the efficiency (if you feel too slow) is to calculate ‘LOS location’ at the beginning, and then use this for all of the images. In this case, you need to re-define tropo_icams_sar as one sub-funciton of tropo_icams.py.
From: Yuan-Kai Liu ***@***.***>
Reply to: ymcmrs/ICAMS ***@***.***>
Date: Tuesday, 25 April 2023 at 6:07 AM
To: ymcmrs/ICAMS ***@***.***>
Cc: Yunmeng Cao ***@***.***>, Mention ***@***.***>
Subject: Re: [ymcmrs/ICAMS] `tropo_icams_sar.read_par_orb`: modify to read isce2 `IW1.xml` (Issue #3)


Reading orbits and timings from ISCE2 IW*.xml works well for me. Thanks

Just a follow-up question about computation. I am working on a longer track spanning ~6 latitude degrees across 7 SAR tracks.
The get_LOS_parameters<https://github.com/ymcmrs/ICAMS/blob/main/icams/tropo_icams_sar.py#L439-L440> (Start to calc LOS atmospheric parameters ...) step seems to be the most time-consuming part. I assume this is not parallelized now (OMP_NUM_THREADS) now?

Have you run into an issue that runs super slow? E.g., only calculates 20 dates of LOS parameters with 12 hours of computation.

**Comment by yuankailiu** [comment]
That seems to be the right way for me. Thanks.

**Comment by yuankailiu** [comment]
it is true that tropo_icams.py calls tropo_icams_sar.py repeatedly for the time series.

After looking at the `[tropo_icams_sar.py](https://github.com/ymcmrs/ICAMS/blob/main/icams/tropo_icams_sar.py#L429-L440)`, it does check the LOS location file (`lat_intp_binary`) and does not repeatedly compute the locations.

The main sluggishness occurs on the major computation in`[ut.get_LOS_parameters](https://github.com/ymcmrs/ICAMS/blob/82d735535427a8e5c21301b507a25e4ef454fd8e/icams/_utils.py#L1122)` where I think it uses `pykrige` to upsample/weight the ERA5 grids to get LosP, LosT, LosV at each level. So it depends on the size of the model grids (my InSAR spatial coverage).

I guess I can, in turn, use Python multithreading to parallelize the dates in this loop in `[tropo_icams.py](https://github.com/ymcmrs/ICAMS/blob/main/icams/tropo_icams.py#L201-L205)` to call several `tropo_icams_sar.py` at the same time.
